merge-key: "prod/masdemo1/inst1"
ibm_mas_suite_configs:
  - mas_config_name: "inst1-bas-system"
    mas_config_chart: ibm-mas-bas-config
    mas_config_scope: system
    mas_workspace_id: inst1ws1
    mas_application_id:
    mas_config_kind: "bascfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    dro_api_token: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/dro#dro_api_token>
    dro_endpoint_url: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/dro#dro_url>
    dro_contact:
      email: user@example.com
      first_name: hilmi
      last_name: tekin
    dro_ca:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIFozCCBIugAwIBAgISBcE3gxKarwId53pq5JlHgc3jMA0GCSqGSIb3DQEBCwUA
        MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
        EwNSMTIwHhcNMjUxMTI3MTIwMTAyWhcNMjYwMjI1MTIwMTAxWjA4MTYwNAYDVQQD
        Ey02OTI4NDk2ZGZjNGE4NDQxZmJlZDFkOTAub2NwLnRlY2h6b25lLmlibS5jb20w
        ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDWW2RDoPOCAan24qmBftnR
        IeKdB8imtzyDifRGYemj+9TYA7Qub6HsYDWz5ptKikCveC9jJAmzIFOzh5sOcYy+
        0BFGWpBuuA+NpPfBZnHX/U660L1J4SJ2wo1zM3wUV/0r2x76xHPuV7vCcInAuF3i
        4fy3F0KLvvFyDfVz6XWR9RUo9AW8Q9nOZjgfnKXuSuks5GvbtDoSspttA1LWNlrj
        NIWPcstu6CPw+z3niFmKHu7olD7hadoc3hIj1LGcbToNr/etIdjEyZCHGyb3yoCr
        chK4OuezJBRW1MDeu8I3rrTZsrwsgmIz7APJJ7zZA/p0EGJRoU+wTdPcurJhMGoZ
        AgMBAAGjggKqMIICpjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
        AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFJeVF15Xtl6+T1ai
        5eiy9UDGTVsjMB8GA1UdIwQYMBaAFAC1KfItjm8x6JtMrXg++tzpDNHSMDMGCCsG
        AQUFBwEBBCcwJTAjBggrBgEFBQcwAoYXaHR0cDovL3IxMi5pLmxlbmNyLm9yZy8w
        gaMGA1UdEQSBmzCBmII0Ki5hcHBzLjY5Mjg0OTZkZmM0YTg0NDFmYmVkMWQ5MC5v
        Y3AudGVjaHpvbmUuaWJtLmNvbYItNjkyODQ5NmRmYzRhODQ0MWZiZWQxZDkwLm9j
        cC50ZWNoem9uZS5pYm0uY29tgjFhcGkuNjkyODQ5NmRmYzRhODQ0MWZiZWQxZDkw
        Lm9jcC50ZWNoem9uZS5pYm0uY29tMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC8GA1Ud
        HwQoMCYwJKAioCCGHmh0dHA6Ly9yMTIuYy5sZW5jci5vcmcvMTAwLmNybDCCAQQG
        CisGAQQB1nkCBAIEgfUEgfIA8AB3AEmcm2neHXzs/DbezYdkprhbrwqHgBnRVVL7
        6esp3fjDAAABmsVlxaEAAAQDAEgwRgIhAPQ9hUtoKFjzTNTnavo/8neIaygU3irO
        a67IWof7yYFZAiEAkF/EzalEt0SRRFVj93Qtx0wxKEPFQkK7KIXkzKw7m2YAdQCW
        l2S/VViXrfdDh2g3CEJ36fA61fak8zZuRqQ/D8qpxgAAAZrFZcX1AAAEAwBGMEQC
        IGC+RQAaW8CdVxiRhytBjxRN8CZze2eywllBWrjSQ6FFAiAuFhcnF2LsVPlZbDw0
        LAiWRY4iEAcV3nxUAmJTjMLp4DANBgkqhkiG9w0BAQsFAAOCAQEAi/lUeYi4LHYT
        OiOuRY55x/uRq13zBXZuWgWt/r5fjVZ3vQS6fYvw5jCyU7SPh05XHQEyWB8Ax1SG
        gNld82wtkrDqb2+CkMbi3IUy2dQFIJ7cnyqp9IOKm5WmSCSK52nhb2vriRLYQm1j
        I0exMwrEM/TNS/9my19pzOW2lHE1mC+KK0OcgT+qf5L2QxGFaLEYzxo28J8BEICM
        iVOCktVF2xu0K6j8sbg4zPqaR92wZg3BJDFzdh1Sx8YAhNrVRWXZiHnvBdVnAWL/
        /vvdZSc/CuFzDe1D2J2CrJisTtVT4SOUlYcWdrALSQHhWia5nELOuu9YpicgTgP4
        IZOOeqBUoQ==
        -----END CERTIFICATE-----

        -----BEGIN CERTIFICATE-----
        MIIFBjCCAu6gAwIBAgIRAMISMktwqbSRcdxA9+KFJjwwDQYJKoZIhvcNAQELBQAw
        TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
        cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
        WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
        RW5jcnlwdDEMMAoGA1UEAxMDUjEyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA2pgodK2+lP474B7i5Ut1qywSf+2nAzJ+Npfs6DGPpRONC5kuHs0BUT1M
        5ShuCVUxqqUiXXL0LQfCTUA83wEjuXg39RplMjTmhnGdBO+ECFu9AhqZ66YBAJpz
        kG2Pogeg0JfT2kVhgTU9FPnEwF9q3AuWGrCf4yrqvSrWmMebcas7dA8827JgvlpL
        Thjp2ypzXIlhZZ7+7Tymy05v5J75AEaz/xlNKmOzjmbGGIVwx1Blbzt05UiDDwhY
        XS0jnV6j/ujbAKHS9OMZTfLuevYnnuXNnC2i8n+cF63vEzc50bTILEHWhsDp7CH4
        WRt/uTp8n1wBnWIEwii9Cq08yhDsGwIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
        hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
        /wIBADAdBgNVHQ4EFgQUALUp8i2ObzHom0yteD763OkM0dIwHwYDVR0jBBgwFoAU
        ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
        hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
        A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
        AQELBQADggIBAI910AnPanZIZTKS3rVEyIV29BWEjAK/duuz8eL5boSoVpHhkkv3
        4eoAeEiPdZLj5EZ7G2ArIK+gzhTlRQ1q4FKGpPPaFBSpqV/xbUb5UlAXQOnkHn3m
        FVj+qYv87/WeY+Bm4sN3Ox8BhyaU7UAQ3LeZ7N1X01xxQe4wIAAE3JVLUCiHmZL+
        qoCUtgYIFPgcg350QMUIWgxPXNGEncT921ne7nluI02V8pLUmClqXOsCwULw+PVO
        ZCB7qOMxxMBoCUeL2Ll4oMpOSr5pJCpLN3tRA2s6P1KLs9TSrVhOk+7LX28NMUlI
        usQ/nxLJID0RhAeFtPjyOCOscQBA53+NRjSCak7P4A5jX7ppmkcJECL+S0i3kXVU
        y5Me5BbrU8973jZNv/ax6+ZK6TM8jWmimL6of6OrX7ZU6E2WqazzsFrLG3o2kySb
        zlhSgJ81Cl4tv3SbYiYXnJExKQvzf83DYotox3f0fwv7xln1A2ZLplCb0O+l/AK0
        YE0DS2FPxSAHi0iwMfW2nNHJrXcY3LLHD77gRgje4Eveubi2xxa+Nmk/hmhLdIET
        iVDFanoCrMVIpQ59XWHkzdFmoHXHBV7oibVjGSO7ULSQ7MJ1Nz51phuDJSgAIU7A
        0zrLnOrAj/dfrlEWRhCvAgbuwLZX1A2sjNjXoPOHbsPiy+lO1KF8/XY7
        -----END CERTIFICATE-----
  - mas_config_name: "inst1-jdbc-wsapp-inst1ws1-manage"
    mas_config_chart: ibm-jdbc-config
    mas_config_scope: wsapp
    mas_workspace_id: inst1ws1
    mas_application_id: manage
    mas_config_kind: "jdbccfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    jdbc_type: incluster-db2
    jdbc_connection_url_additional_params:
    jdbc_instance_name: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#jdbc_instance_name>
    jdbc_instance_username: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/credentials#username>
    jdbc_instance_password: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/credentials#password>
    mas_config_dir: /mascli/mongoce
    jdbc_connection_url: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#jdbc_connection_url>
    jdbc_route: default
    db2_dbname: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#db2_dbname>
    db2_namespace: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#db2_namespace>
    app_suite_jdbccfg_labels:
      mas.ibm.com/applicationId: "manage"
      mas.ibm.com/configScope: application
      mas.ibm.com/instanceId: "inst1"
    system_suite_jdbccfg_labels:
      mas.ibm.com/configScope: system
      mas.ibm.com/instanceId: "inst1"
    ws_suite_jdbccfg_labels:
      mas.ibm.com/configScope: workspace-application
      mas.ibm.com/instanceId: "inst1"
      mas.ibm.com/workspaceId: "inst1ws1"
    wsapp_suite_jdbccfg_labels:
      mas.ibm.com/applicationId: "manage"
      mas.ibm.com/configScope: workspace-application
      mas.ibm.com/instanceId: "inst1"
      mas.ibm.com/workspaceId: "inst1ws1"
    jdbc_ca_pem:
      crt: |
        <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#ca_b64 | base64decode>
  - mas_config_name: "inst1-mongo-system"
    mas_config_chart: ibm-mas-mongo-config
    mas_config_scope: system
    mas_workspace_id: inst1ws1
    mas_application_id:
    mas_config_kind: "mongocfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    username: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/mongo#username>
    password: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/mongo#password>
    config:
      hosts:
        - host: mas-mongo-ce-0.mas-mongo-ce-svc.mongoce.svc.cluster.local
          port: 27017
        - host: mas-mongo-ce-1.mas-mongo-ce-svc.mongoce.svc.cluster.local
          port: 27017
        - host: mas-mongo-ce-2.mas-mongo-ce-svc.mongoce.svc.cluster.local
          port: 27017
      authMechanism: DEFAULT
      configDb: admin
      credentials:
        secretName: "system-mongo-credentials"
    certificates:
      - alias: ca
        crt: |
          -----BEGIN CERTIFICATE-----
          MIIBvjCCAWWgAwIBAgIQb4u6tGWTBl+7yGttCwaNrjAKBggqhkjOPQQDAjAXMRUw
          EwYDVQQDEwxtb25nby1jYS1jcnQwHhcNMjUxMTI3MjMyNTEwWhcNNDUxMTIyMjMy
          NTEwWjAXMRUwEwYDVQQDEwxtb25nby1jYS1jcnQwWTATBgcqhkjOPQIBBggqhkjO
          PQMBBwNCAASlqcSeEYCcRiRfZ937Qvn6rlfz1S+q49vn2LvggVfG+8Q02D4TAfSv
          6A0dLszjyy2Smm1FQavYdTPxLolIXvAko4GSMIGPMA4GA1UdDwEB/wQEAwICpDAP
          BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTVMAucRHOWdBT4j+Yh4YVmARWdqDBN
          BgNVHREERjBEgiwqLm1hcy1tb25nby1jZS1zdmMubW9uZ29jZS5zdmMuY2x1c3Rl
          ci5sb2NhbIIJMTI3LjAuMC4xgglsb2NhbGhvc3QwCgYIKoZIzj0EAwIDRwAwRAIg
          ZrIktlvvy0sRM+N8rfBbFOmzOQ9Ca2tZW+DndJgkaHQCIGlvn4f7CcbJot+2hoku
          7a/vqczmSRBqok2fvKQQhdzb
          -----END CERTIFICATE-----
  - mas_config_name: "inst1-sls-system"
    mas_config_chart: ibm-mas-sls-config
    mas_config_scope: system
    mas_workspace_id: inst1ws1
    mas_application_id:
    mas_config_kind: "slscfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    registration_key: <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/sls#registration_key>
    url: "https://sls.mas-inst1-sls.svc"
    ca:
      crt: |
        <path:arn:aws:secretsmanager:us-east-1:149536496842:secret:prod/masdemo1/inst1/sls#ca_b64 | base64decode>
